// <auto-generated />
namespace TaskBoard.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Extending_with_projects_persons : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Extending_with_projects_persons));
        
        string IMigrationMetadata.Id
        {
            get { return "202102181304409_Extending_with_projects_persons"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
